services:
  db:
    image: postgres:15
    container_name: crm-postgres
    restart: always
    environment:
      POSTGRES_DB: crm_telefonia
      POSTGRES_USER: arthur
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
